### ISSUE TITLE
AttributeError: 'PurePosixPath' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by carlwgeorge** [carlwgeorge/repomd#5]
0.2.0 introduced a bug that prevents repomd from loading a URL.

```python
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    repo = repomd.load('https://mirror.rackspace.com/centos/7/updates/x86_64/')
  File "/usr/lib/python3.7/site-packages/repomd.py", line 20, in load
    with urllib.request.urlopen(base / 'repodata' / 'repomd.xml') as response:
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 516, in open
    req.timeout = timeout
AttributeError: 'PurePosixPath' object has no attribute 'timeout'
```

**Comment by carlwgeorge** [comment]
6876975d8ff5e6b2d9fd1a5c1bb5385cfab732f1 is the problem.  `urlopen` doesn't accept `PurePosixPath` objects.  Even if it did, using `PurePosixPath` on the entire URL concatenates the consecutive slashes in the scheme.  The path needs to be parsed out from the URL.
